; GTA V R.E.A.L. mod Release 7

[Defaults]

; F11         Activate hotkeys - off at start
Hotkeys = 0

; 0           Select stereo mode in cutscenes (normal, dynamic, flat screen) - dynamic at start
StereoInCutscenes = 1

; T           Select dominant eye for aiming down sights (none, left, right) - right at start
DominantEye = 0

; Y           Select heading control (always, only when aiming, never) - always at start
HeadingControl = 0

; J           Select pitch mode in cutscenes (absolute, relative, cut relative) - cut relative at start
CutscenePitchMode = 2

; N           Show FPS counter - off at start
ShowFPS = 0

; End         Activate gyro stabilization of view in vehicle - off at start
GyroVehicle = 0

;             Select universal FOV fix (never, only cutscenes, only aiming, always) - always at start
UniversalFOVFix = 3

; NUMPAD.     Select zoom/FOV override (never, only cutscenes, always except cutscenes, always) - never at start
ZoomOverride = 0

; NUMPAD2     Activate stereo rendering (alternate eyes) - on at start
Stereo = 0

;             Select VR API to use (autodetect, Oculus, OpenVR, OpenXR) - autodetect by default
VRAPI = 0
